server:
  port: 7001
  servlet:
    session:
      cookie:
        name: emake-auth
        http-only: true
# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.47:3306/emake?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  redis:
    database: 0
    host: 192.168.0.47
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 10  # 连接池中的最小空闲连接
ignore:
  urls:
    - /authentication/**
    - /css/*.css
    - /js/*.js
    - /actuator/**
    - /hystrix/**
    - /loggers/**
    - /mobile/cookie
    - /oauth/token_key

