server:
  port: 4040
  servlet:
    context-path: /sso

security:
  oauth2:
#    sso:
#      # 跳转到SSO的登录路径默认为/login.
#      loginPath: http://localhost:7001/authentication/require
    client:
      clientId: emake
      clientSecret: emake
      accessTokenUri: http://localhost:7001/oauth/cookie
      userAuthorizationUri: http://localhost:7001/oauth/authorize
#      clientAuthenticationScheme: form
      scope: server
    resource:
#      jwt:
#        key-uri:  http://localhost:7001/oauth/token_key
      user-info-uri:  http://localhost:7001/authentication/member
      preferTokenInfo: true
      token-info-uri: http://localhost:7001/oauth/check_token

spring:
  application:
    name: emake-sso-client
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.47:3306/emake?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    database: 0
    host: 192.168.0.47
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 10  # 连接池中的最小空闲连接
ignore:
  urls:
    - /css/*.css
    - /js/*.js
    - /actuator/**
    - /hystrix/**
    - /metrics/**
    - /loggers/**





